# Base16 Catppuccin Mocha - Hyprland Appearance
# Author: https://github.com/catppuccin/catppuccin

# Colors (Base16)
$base00 = rgb(1e1e2e)
$base01 = rgb(181825)
$base02 = rgb(313244)
$base03 = rgb(45475a)
$base04 = rgb(585b70)
$base05 = rgb(cdd6f4)
$base06 = rgb(f5e0dc)
$base07 = rgb(b4befe)
$base08 = rgb(f38ba8)
$base09 = rgb(fab387)
$base0A = rgb(f9e2af)
$base0B = rgb(a6e3a1)
$base0C = rgb(94e2d5)
$base0D = rgb(89b4fa)
$base0E = rgb(cba6f7)
$base0F = rgb(f2cdcd)

decoration {
    rounding = 10

    blur {
        enabled = true
        size = 5
        passes = 2
        new_optimizations = true
        xray = false
    }

    shadow {
        enabled = true
        range = 30
        render_power = 2
        color = rgba(cba6f7aa)
        color_inactive = rgba(1e1e2e00)
    }
}

animations {
    enabled = true

    bezier = myBezier, 0, 0, 1, 1
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = smoothIn, 0.25, 1, 0.5, 1

    animation = windows, 1, 4, myBezier, slide
    animation = windowsOut, 1, 4, smoothOut, slide
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 0, 5, smoothIn
    animation = workspaces, 1, 6, default
}