# Autostart applications

exec-once = ironbar
exec-once = mako
exec-once = awww-daemon
exec-once = awww img ~/.config/wallpapers/catppuccin-mocha/default.png --transition-type grow --transition-pos 0.5,0.5 --transition-duration 2

# System tray apps (you likely have these from KDE)
exec-once = nm-applet --indicator
exec-once = blueman-applet

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Idle daemon (screens off after 15 min)
exec-once = hypridle
